namespace TwitchTTS{
  [default_interface] runtimeclass TextToSpeechElement : Windows.UI.Xaml.Controls.MediaPlayerElement {
    TextToSpeechElement();
    String GetText();
    void SetText(String text);
  };
}